---
- name: Creates directory
  file: path=~/webapp state=directory

- name: Unarchive a file that needs to be downloaded from S3
  unarchive:
    src: https://s3-us-west-2.amazonaws.com/techops-interview-webapp/webapp.tar.gz
    dest: ~/webapp
    remote_src: yes

- name: Check if webserver is running
  tags: webserver
  shell: ps aux | grep "dist/example" | grep -v grep
  ignore_errors: yes
  changed_when: false
  register: service_webapp_status

- name: Start webapp
  tags: webserver
  shell: cd ~/webapp; dist/example-webapp-linux </dev/null >/dev/null 2>&1 &
  when: service_webapp_status.rc == 1
